# Sample docker-compose.yaml deploying Pi-hole and Unbound
# with a Bridged Network.
# This example needs to be modified to reflect your network environment,
# especially the values in angle brackets (<>) must be adapted to your needs.
# This file is the one I'm using and was slightly modified with added IPv6
# support (which I'm not using currently).

services:
  pihole:
    container_name: pi-hole
    image: pihole/pihole:latest
    hostname: pi-hole
    domainname: <yourdomain.lan>
    depends_on:
      - unbound
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    networks:
      dns-network:
        ipv4_address: <PI_HOLE_IPv4_ADDRESS> #e.g. 172.20.0.254
        #ipv6_address: <PI_HOLE_IPv6_ADDRESS> #e.g. fd11:aa:1234:1234::506
    dns:
      - <UNBOUND_IP_ADDRESS> #e.g. 172.20.0.253 or fd11:aa:1234:1234::505
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: <YOURTIMEZONE> #e.g. "Europe/Berlin"
      FTLCONF_webserver_api_password: '<YOURPASSWORD>' #Set your password
      FTLCONF_dns_upstreams: '172.20.0.253#5335;' #Your unbound ipv4 address
    volumes:
      - <LOCAL_PIHOLE_VOLUME_PATH>:/etc/:rw #Your local path to Pi-hole
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    domainname: <yourdomain.lan>
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    networks:
      dns-network:
        ipv4_address: <UNBOUND_IPv4_ADDRESS> #e.g. 172.20.0.253
        #ipv6_address: <UNBOUND_IPv6_ADDRESS> #e.g. fd11:aa:1234:1234::505
    environment:
      TZ: <YOURTIMEZONE> #e.g. "Europe/Berlin"
      UNBOUND_UID: 1000 #optional
      UNBOUND_GID: 1000 #optional
      HEALTHCHECK_PORT: 5335 #optional
      EXTENDED_HEALTHCHECK: false #optional
      EXTENDED_HEALTHCHECK_DOMAIN: <Domain/host to query> #optional
      ENABLE_STATS: false #optional
    volumes:
      - ./unbound.conf:/usr/local/unbound/unbound.conf:rw #Your local path to Unbound
      - ./conf.d/:/usr/local/unbound/conf.d/:rw
      - ./log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - ./zones.d/:/usr/local/unbound/zones.d/:rw
    restart: unless-stopped
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

networks:
  dns-network:
    #enable_ipv6: <false> #Enable if using IPv6
    driver: bridge
    driver_opts:
      parent: <eth0> #Your parent network interface
    ipam:
      config:
        - subnet: <IPv4_SUBNET> #e.g. 172.20.0.0/24
          gateway: <GATEWAY_IPv4_ADDRESS> #e.g. 172.20.0.1
        #- subnet: <IPv6_SUBNET> #e.g. fd11:aa:1234:1234::/126
        # gateway: <GATEWAY_IPv6_ADDRESS> #e.g. fd11:aa:1234:1234::11
