name: CD Build Nightly Distroless Unbound Docker Image

on:      
  schedule:
    - cron: '0 0 * * mon-fri'
    
jobs: 
  build: 
    runs-on: ubuntu-latest
    
    env:
      DOCKERHUB_SLUG: "madnuttah/unbound"   
      
    steps:
      # - uses: step-security/harden-runner@v2
        # with:
          # egress-policy: block
          # disable-telemetry: true
          # allowed-endpoints: 
            # dl-cdn.alpinelinux.org:443
            # github.com:443
            # docker.io:433
            # index.docker.io:433
            # auth.docker.io:443
            # registry-1.docker.io:443
            # production.cloudflare.docker.com:443
            # objects.githubusercontent.com:443
            # nlnetlabs.nl:443
            # www.internic.net:443
            # keys.openpgp.org:443
            # pipelines.actions.githubusercontent.com:443 
            # actions-results-receiver-production.githubapp.com:443
            # aquasecurity.github.io:433
            # ghcr.io:433
            
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
              
      - name: Set build date
        id: SET_BUILD_DATE
        run: |
          echo IMAGE_BUILD_DATE=$(date -u) >> $GITHUB_OUTPUT
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            IMAGE_BUILD_DATE=${{ steps.SET_BUILD_DATE.outputs.IMAGE_BUILD_DATE }} 
          file: ./unbound/nightly.Dockerfile   
          sbom: ${{ github.event_name != 'pull_request' }}
          provenance: ${{ github.event_name != 'pull_request' }}
          push: ${{ github.event_name != 'pull_request' }}      
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:nightly
            
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        if: ${{ github.event_name != 'pull_request' }}
        with:
          image-ref: ${{ env.DOCKERHUB_SLUG }}:nightly          
          exit-code: '0'
          ignore-unfixed: false
          scan-type: image
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'table'
          