name: CD Security Scan
   
on:   
#  workflow_run:
#    workflows: [CD Check NLnet Labs Unbound Release]
#    types:
#      - completed
    schedule:
      - cron: '0 9 * * *'
    
  
jobs:
  scan:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    env:
      DOCKERHUB_SLUG: "madnuttah/unbound"  
      
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: 
            dl-cdn.alpinelinux.org:443
            github.com:443
            docker.io
            index.docker.io
            auth.docker.io:443
            registry-1.docker.io:443
            production.cloudflare.docker.com:443
            objects.githubusercontent.com:443
            www.nlnetlabs.nl:443
            www.internic.net:443
            keys.openpgp.org:443
            pipelines.actions.githubusercontent.com:443 
            actions-results-receiver-production.githubapp.com:443
    
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        if: ${{ github.event_name != 'pull_request' }}
        with:
          image-ref: ${{ env.DOCKERHUB_SLUG }}:latest    
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          scan-type: image
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name: Upload SARIF result
        id: UPLOAD_SARIF
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif.output.json
